### ISSUE TITLE
Be compatible with ember-cli 0.2+

### ISSUE THREAD

**Issue by mixonic** [Vestorly/ember-cli-emblem-hbs-printer#1]
https://github.com/201-created/ember-cli-emblem-hbs-printer/blob/master/index.js#L38 is no longer valid.

See notes:

* https://github.com/ember-cli/ember-cli/releases/tag/v0.2.0-beta.1
* https://github.com/ember-cli/ember-cli-htmlbars/pull/38
* https://github.com/kimroen/ember-cli-coffeescript/pull/60

**Comment by akatov** [comment]
+1 please

**Comment by Evkin** [comment]
+1

**Comment by atsjj** [comment]
In order to get around the *ordering* block in ember-cli, I've got a fork running that will place the printer before the Handlebars and HTMLBars compilers for the current 0.2.0-beta and 0.1.15.

https://github.com/atsjj/ember-cli-emblem-hbs-printer

Since there is a hack that re-arranges the registry's template array, I didn't feel comfortable placing a PR for this code. However, when 0.2.0 becomes stable, I'd be more than happy to remove the hack and submit a PR.

**Comment by buschtoens** [comment]
First of all, thank you so much @atsjj! Can't wait to try it out tomorrow!

However, I don't really understand the second paragraph (might be the lack of sleep, might be me just being stupid). Why does the hack get "okay" when 0.2.0 becomes stable? Or do you think, that they will include an official API for (re-)ordering the plugins and the hack won't be necessary anymore?

**Comment by atsjj** [comment]
Unless I read it wrong, I think one of the blocking issues for 0.2 is addon ordering.

Good news if I'm wrong, I'll do a PR for this bad boy and we should be good.

**Comment by atsjj** [comment]
Stupid me. TL:DR; yes, I think 0.2 will allow me to remove the hack.

**Comment by buschtoens** [comment]
I was misinformed as well. Haha. 

But I really appreciate you sharing this fork with us, so I can finally continue my work on 0.2.0. I don't like keeping my client waiting. Smile

**Comment by mphasize** [comment]
Good news! ember-cli registry bug just got resolved: https://github.com/ember-cli/ember-cli/issues/3396 :-)

**Comment by atsjj** [comment]
@mphasize very cool! Thanks for the heads up!

I will go ahead and remove my hack when they tear off a new release, either beta or stable.

I'm wondering if I should (eventually) go ahead an lock the organization method to versions less than 0.2. Feedback?

**Comment by mphasize** [comment]
Looking at the readme of this repo, 1.x versions of ember-cli should work. So the hack is needed for a very specific set of ember-cli versions only (as far as I understand).
As far as I'm concerned I'm happy when I can upgrade to ember-cli 2.0 and use emblem again without any hacks. :-)

**Comment by mixonic** [comment]
Word on the street is that https://github.com/201-created/ember-cli-emblem-hbs-printer/pull/2 should work fine with 0.2.0. I'm actually very uncertain what is being changed for 0.2.0 support here, but I'll attempt to rebase that branch and land test it in a 0.2.0 app (though if someone else wants to pick this up, I would definitely appreciate it since I'm a bit disconnected).

**Comment by mphasize** [comment]
ember-cli 0.2.0 got released in the meantime. Does that mean that the emblem printer is ready to go now? :-)

**Comment by atsjj** [comment]
@mphasize I'm going to upgrade from the beta today and then switch back to the mainline Emblem printer. I expect that everything will just work. I'll post an issue if it doesn't!

**Comment by mixonic** [comment]
ember-cli-emblem-hbs-printer 0.2.0 was released three days ago, works with ember-cli 0.2.0.

**Comment by joebartels** [comment]
should we update README @mixonic

**Comment by mixonic** [comment]
@joebartels if it says something to the contrary, please do!

While you make a patch, you may want to update the repo URL in the `package.json` :-)
