### ISSUE TITLE
Failed in conjunction with other plugins

### ISSUE THREAD

**Issue by aliaksandrb** [Vestorly/ember-cli-emblem-hbs-printer#11]
Hi!

Got an failed application build when `ember-cli-emblem-hbs-printer` used in conjunction with `ember-cli-pagination`.

I wanted to add my custom template for pagination as `ember-cli-pagination` allows to do it by providing own `page-numbers.hbs` component.

But if I write this component as emblem - my build fails with an error:

```bash
Error: EEXIST, file already exists '.../frontend/tmp/template_compiler-tmp_dest_dir-aUV6gkgA.tmp/frontend/templates/components/page-numbers.hbs'
```
Clearing the `/frontend/tmp/` folder doesn't help.

Looking into source of  `ember-cli-emblem-hbs-printer` I've notices such code:
```javascript
function copyPreserveSync (src, dest, srcStats) {
  if (srcStats == null) srcStats = fs.statSync(src)
  if (srcStats.isFile()) {
    var content = fs.readFileSync(src)
    fs.writeFileSync(dest, content, { flag: 'wx' })
    fs.utimesSync(dest, srcStats.atime, srcStats.mtime)
  } else {
    throw new Error('Unexpected file type for ' + src)
  }
}
```

So as we can see the writeFileSync flag is 'wx' that failing if the file exists.

Changing it to simple 'w' does solve the problem.

Does it made intentionally to prevent overrides and should be fixed by some workarounds or an issue?

**Comment by aliaksandrb** [comment]
One more interesting thing: even we change flag to 'w' and application builds successfully our template is not propagated and just default is used.
It may be a problem with an `ember-cli-pagination`, I am not sure, but at the same time seems that `.emblem` template builds just after pagination plugin initialization so it (pagination) doesn't know about it and uses default. Could it be the case?
From first look seems that `ember-cli-pagination` doesn't use any special code to check if the template is exist, using default ember-cli logic.

**Comment by mixonic** [comment]
Can you `ls` the directory in app/? Perhaps there is both an hbs and emblem 
file on disk?

Best,

-Matthew

**Comment by bantic** [comment]
@aliaksandrb I confirmed this. The first error you describe will happen any time there is an emblem template with the same name/path as a handlebars template. For instance, if you have an "index.hbs" and a "index.emblem" in the same directory, you'll see that error.  When you are using ember-cli-pagination, it provides a file at [`templates/components/page-numbers.hbs`](https://github.com/mharris717/ember-cli-pagination/blob/master/app/templates/components/page-numbers.hbs) that gets merged into your app tree by ember-cli. If your app tree also has the same file but with an emblem extension, you get this error.

The ember-cli behavior for this situation without using emblem is that the "app version" wins (silently) — i.e. the file at app/templates/components/page-numbers.hbs is used in favor of the file the addon provides at templates/components/page-numbers.hbs.

We need to change this printer so that it has the same behavior — emblem templates in your app code should "win" over templates of the same name (regardless of extension) provided via addons.

**Comment by aliaksandrb** [comment]
@mixonic @bantic sorry guys, but seems that it's reproducible even when there only one file in the directory:
```bash
$ rm -rf ./frontend/tmp/*
$ ls app/templates/components/
page-numbers.emblem
```
```bash
version: 0.2.1
BuildingBuilding.Building..Building...
EEXIST, file already exists '/frontend/tmp/template_compiler-tmp_dest_dir-Z6VYqng4.tmp/frontend/templates/components/page-numbers.hbs'
Error: EEXIST, file already exists '/frontend/tmp/template_compiler-tmp_dest_dir-Z6VYqng4.tmp/frontend/templates/components/page-numbers.hbs'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.writeFileSync (fs.js:1103:15)
    at Object.copyPreserveSync (/frontend/node_modules/ember-cli-emblem-hbs-printer/node_modules/broccoli-filter/node_modules/broccoli-kitchen-sink-helpers/index.js:150:8)
```

**Comment by mixonic** [comment]
@aliaksandrb the pagination addon adds its own file as a `.hbs`:

* https://github.com/mharris717/ember-cli-pagination/tree/master/app/templates/components

If you want to replace that file, you will need to use the `.hbs` extension to match it. Unfortunately this is the nature of Ember plugins. The only thing we could do would be overwrite hbs files when they exist, but I'm feel this may cause more problems than it would solve. Or possible we could run emblem over the app code before it was merged with addons (/cc @rwjblue). This seems very tricky.

I'm going to close this with the suggestion that you overwrite the file exactly as it exists in the addon, but if more people have this issue we can re-visit. Thanks @aliaksandrb!

**Comment by aliaksandrb** [comment]
@mixonic ok, thanks for detailed explanation, I though that only template in the `app` folder should not conflict with emblem ones, not in the `addons`. I'm sorry for this opened issue.

**Comment by mixonic** [comment]
@aliaksandrb the default addon behavior is that they have two folders: `app` and `addon`. The `app` folder is merged with your own.

I talked to Robert last night and kick around a few ideas on how we might improve this in the long term. You raised a really interesting case!
