### ISSUE TITLE
Problem with rendering inner template

### ISSUE THREAD

**Issue by aliaksandrb** [Vestorly/ember-cli-emblem-hbs-printer#7]
Hi!

Let me describe the problem:
Let we have have such simple `application.emblem`:
```slim
header
  article
    .logo
      h1
        a href="#" Test Project

section#main
  == outlet

footer
```
and one simple root route 'users' which just retrieve 'user' from the store.

The template for `users.emblem`:

```slim
article#users
  h1 Users
  ul
    each user in controller
      li = user.firstName
```
So when I make an request to `/`, the `application.emblem` template is correctly rendered, the Ember inspector shows availability of retrieved data,  and the `users.emblem` template is rendered **but** not visible.
If I open inspector I could see that `section#main` has an 0 width.
![Image](https://i.imgur.com/112xLo0.png)

If I change my `users.emblem` to `users.hbs` and update content accordingly, everything is working fine, and list is displaying.

Am I doing something wrong or why the `.emblem` sub-template doesn't render?

Stack used:
ember: 1.10.0
node: 0.12.0
ember-cli-emblem-hbs-printer: 0.2.1
ember-cli-htmlbars: 0.7.4
ember-cli: 0.2.0

**Comment by aliaksandrb** [comment]
The problem was solved by changing id of article `article#user-list`. Seems that it should differs from the template name?

Sorry a lot for disturbing, enjoying your extension!

**Comment by buschtoens** [comment]
I don't know why this happened with #users, but it doesn't sound like it
should have happened.
Just for the record: Did the .hbs version work with an exact transpilation
of your .emblem version (i.e. did you still use #users in the .hbs version)?

If so, that seems to be a bug in this addon here. If not, this is still
weird behaviour and should be reported upstream, if it isn't by design.

Aliaksandr Buhayeu <notifications@github.com> schrieb am Mo., 23. März 2015
um 12:13 Uhr:

**Comment by buschtoens** [comment]
I don't know why this happened with `#users`, but it doesn't sound like it should have happened.
Just for the record: Did the `.hbs` version work with an exact transpilation of your `.emblem` version (i.e. did you still use `id="users"` in the `.hbs` version)?

If so, that seems to be a bug in this addon here. If not, this is still
weird behaviour and should be reported upstream, if it isn't by design.

**Comment by aliaksandrb** [comment]
@buschtoens no, when I've checked the `.hbs` version,  and it also hadn't displayed but rendered on page. Actually that had gave me the idea to try it with `.emblem` and the reason why I've closed the issue.

Now I starting to understand the reason: it seems to be a collision between actual template name and `.hbs` script name. Assume that while convertation `.emblem` -> `.hbs` when there is no special name (data-name or id) is given than `.hbs` script generated with an id equal to template name. Thats why the second element with the same id rendered with issues.

But it just an assumption..

**Comment by mixonic** [comment]
@aliaksandrb and element ids in the template definitely have nothing to do with the file name. The `.emblem` extension just becomes `.hbs`. Please check your console for an error, and additionally though I am far from an expert in emblem syntax, I think `= outlet` is correct not `== outlet`. In fact I think `outlet` is probably fine.

**Comment by bantic** [comment]
@aliaksandrb Can you try pasting the contents of your users.emblem in here: http://bantic.github.io/try-emblem/
and then put that result in users.hbs? If the users.hbs with that exact transpiled emblem works but it doesn't work as the emblem then yes, there is some sort of a problem.

As you mentioned, there *will* be a name collision between templates with the same filename but different suffixes. I believe that a "users.hbs" file will override a "users.emblem" file at the same path, so when you are trying this with and without emblem please ensure that you have removed the equivalent template with the different file extension.  Usage/changing of a dom id should not affect this output. And  as @mixonic mentions, `== outlet` is most likely not what you want. `= outlet` and `outlet` are identical (to emblem), and one of those would be what you should use.

**Comment by buschtoens** [comment]
Side note: the unescaped expressions section is extremely confusing then. http://emblemjs.com/syntax/

**Comment by aliaksandrb** [comment]
@bantic after that online-convenrtion it behaves pretty the same way: until I change id='users' to something else, it renders but in width-less form.
When I test those changes I just renaming the file, so have no both `.emblem` and `.hbs` at the same time.

@mixonic @bantic I've used the `== outlet` form to prevent html escapes in sub-templates. Changing it to `= outlet` or simple `outlet` still reproduces the same confusing behavior with and id.

**Comment by mixonic** [comment]
@buschtoens I don't know why you would ever use `{{{outlet}}}`. It is definitely a poor suggestion.

@aliaksandrb please use @bantic's URL to generate the handlebars for your template, and paste here as code so we can see what it outputs.

**Comment by aliaksandrb** [comment]
Here it is:

**application.emblem**
```html
<header><article><div class="logo"><h1><a href="#">Test Project</a></h1></div></article></header><section id="main">{{outlet}}</section><footer></footer>
```
(with spacing)
```html
<header>
  <article>
    <div class="logo">
      <h1>
        <a href="#">Test Project</a>
      </h1>
    </div>
  </article>
</header>
<section id="main">
  {{outlet}}
</section>
<footer>
</footer>
```
**users.emblem**
```html
<article id="users"><h1>Users</h1><ul>{{#each user in controller}}<li>{{user.firstName}}</li>{{/each}}</ul></article>
```
(with spacing)
```html
<article id="users">
  <h1>Users</h1>
  <ul>
    {{#each user in controller}}
      <li>{{user.firstName}}</li>
    {{/each}}
  </ul>
</article>
```

**Comment by mixonic** [comment]
@aliaksandrb those templates look 100% sane to me. If you use them in your application (without emblem), I expect you still see your bad behavior. Can you confirm? This would point to something outside of Emblem.
